# 10 практических задач по NumPy

Задачи составлены на основе конспекта по NumPy.  
В каждой задаче есть исходные данные и 2-3 вопроса.  
Решения не приведены - задачи предназначены для самостоятельной практики.

---

## Задача 1. Типы данных и память

```python
import numpy as np

client_id = np.array([100001, 100002, 100003, 100004, 100005])
age = np.array([24, 35, 41, 29, 52])
orders_total = np.array([12, 250, 480, 35, 102])
days_since_last_order = np.array([15, 240, 365, 7, 90])
is_active = np.array([1, 0, 0, 1, 1])
```

### Вопросы

1. Для каждого массива подбери более экономный NumPy-тип данных.
2. Приведи массивы к новым типам через `.astype()`.
3. Проверь, что значения после преобразования не изменились.



In [6]:
import numpy as np

client_id = np.array([100001, 100002, 100003, 100004, 100005])
age = np.array([24, 35, 41, 29, 52])
orders_total = np.array([12, 250, 480, 35, 102])
days_since_last_order = np.array([15, 240, 365, 7, 90])
is_active = np.array([1, 0, 0, 1, 1])

new_client_id = client_id.astype(np.int32)
print("allclose:   ", np.allclose(client_id, new_client_id))
print()
new_age =age.astype(np.int8)
print("allclose:   ", np.allclose(age, new_age))
print()
new_orders_total = orders_total.astype(np.int16)
print("allclose:   ", np.allclose(orders_total, new_orders_total))
print()
new_days_since_last_order = days_since_last_order.astype(np.int16)
print("allclose:   ", np.allclose(days_since_last_order, new_days_since_last_order))
print()
new_is_active = is_active.astype(np.int8)
print("allclose:   ", np.allclose(is_active, new_is_active))
print()


allclose:    True

allclose:    True

allclose:    True

allclose:    True

allclose:    True




## Задача 2. План-факт продаж

```python
import numpy as np

sales_plan = np.array([1_000_000, 1_200_000, 900_000, 1_500_000, 800_000])
sales_fact = np.array([950_000, 1_350_000, 870_000, 1_800_000, 640_000])
```

### Вопросы

1. Посчитай выполнение плана продаж.
2. Найди строки, где план выполнен на 100% и выше.
3. Найди строки, где выполнение ниже 80%.

In [17]:
import numpy as np

sales_plan = np.array([1000000, 1200000, 900000, 1500000, 800000])
sales_fact = np.array([950000, 1350000, 870000, 1800000, 640000])

plan_fact = np.divide(
    sales_fact,
    sales_plan,
    out = np.full(sales_plan.shape, 0, dtype=np.float16),
    where=sales_plan != 0
)*100

print("Выполнение плана продаж -", plan_fact)
print()

good_job = plan_fact >= 100
print("План выполнен на 100 и более % -", plan_fact[good_job])
print()

bad_job = plan_fact < 80
print("План выполнен ниже 80 % -", plan_fact[bad_job])
print()



Выполнение плана продаж - [ 95.  112.5  96.7 120.   80. ]

План выполнен на 100 и более % - [112.5 120. ]

План выполнен ниже 80 % - []



In [18]:
import numpy as np

sales_plan = np.array([1_000_000, 1_200_000, 900_000, 1_500_000, 800_000])
sales_fact = np.array([950_000, 1_350_000, 870_000, 1_800_000, 640_000])

plan_fact = np.divide(
    sales_fact,
    sales_plan,
    out=np.full(sales_plan.shape, 0, dtype=np.float64),
    where=sales_plan != 0
) * 100

print("Выполнение плана продаж (%):", np.round(plan_fact, 2))
print()

good_job = plan_fact >= 100
print("План выполнен на 100%+ (индексы):", np.where(good_job)[0])
print("Значения факт/план:", sales_fact[good_job], "/", sales_plan[good_job])
print("Выполнение (%):", plan_fact[good_job])
print()

bad_job = plan_fact < 80
print("Выполнение ниже 80% (индексы):", np.where(bad_job)[0])
print("Значения факт/план:", sales_fact[bad_job], "/", sales_plan[bad_job])
print("Выполнение (%):", plan_fact[bad_job])

Выполнение плана продаж (%): [ 95.   112.5   96.67 120.    80.  ]

План выполнен на 100%+ (индексы): [1 3]
Значения факт/план: [1350000 1800000] / [1200000 1500000]
Выполнение (%): [112.5 120. ]

Выполнение ниже 80% (индексы): []
Значения факт/план: [] / []
Выполнение (%): []



## Задача 3. KPI менеджеров

```python
import numpy as np

sales_completion = np.array([0.95, 1.12, 0.97, 1.20, 0.80])
new_clients_completion = np.array([1.00, 0.75, 1.10, 0.90, 0.60])
op_kpi = np.array([0.90, 1.05, 0.85, 1.00, 0.70])
```

Итоговый индекс считается по формуле:

```text
продажи - 50%
новые клиенты - 30%
операционный KPI - 20%
```

### Вопросы

1. Посчитай итоговый индекс для каждого менеджера.
2. Найди менеджеров, у которых индекс ниже 0.85.
3. Найди максимальный и средний индекс.

In [20]:
import numpy as np

sales_completion = np.array([0.95, 1.12, 0.97, 1.20, 0.80])
new_clients_completion = np.array([1.00, 0.75, 1.10, 0.90, 0.60])
op_kpi = np.array([0.90, 1.05, 0.85, 1.00, 0.70])


total_index = sales_completion * 0.5 + new_clients_completion * 0.3 + op_kpi * 0.2
print(total_index)
print()

bad_managers = total_index < 0.85
print(total_index[bad_managers])
print()

max_index = total_index.max()
print("Максимальный индекс ", max_index)
print()

avg_index = total_index.mean()
print("Средний индекс ", avg_index)
print()

[0.955 0.995 0.985 1.07  0.72 ]

[0.72]

Максимальный индекс  1.07

Средний индекс  0.945




## Задача 4. Матрица менеджеры x месяцы

```python
import numpy as np

sales_completion = np.array([
    0.90, 1.10, 0.95,
    1.20, 0.80, 1.00,
    0.70, 0.85, 0.95,
    1.05, 1.15, 1.25
])
```

Это выполнение плана 4 менеджеров за 3 месяца.  
Данные идут подряд: сначала 3 месяца первого менеджера, потом 3 месяца второго и так далее.

### Вопросы

1. Преобразуй массив в матрицу формы `(4, 3)`.
2. Посчитай среднее выполнение по каждому менеджеру.
3. Посчитай среднее выполнение по каждому месяцу.

In [31]:
import numpy as np

sales_completion = np.array([
    0.90, 1.10, 0.95,
    1.20, 0.80, 1.00,
    0.70, 0.85, 0.95,
    1.05, 1.15, 1.25
])

matrix = sales_completion.reshape(4, 3)
print("Матрица (менеджеры × месяцы):")
print(matrix)

# axis=1 — среднее по столбцам (месяцам) для каждой строки (менеджера)
avg_by_manager = matrix.mean(axis=1)
print("\nСреднее выполнение по каждому менеджеру:")
for i, val in enumerate(avg_by_manager):
    print(f"  Менеджер {i + 1}: {val:.3f}")

# axis=0 — среднее по строкам (менеджерам) для каждого столбца (месяца)
avg_by_month = matrix.mean(axis=0)
print("\nСреднее выполнение по каждому месяцу:")
for i, val in enumerate(avg_by_month):
    print(f"  Месяц {i + 1}: {val:.3f}")

Матрица (менеджеры × месяцы):
[[0.9  1.1  0.95]
 [1.2  0.8  1.  ]
 [0.7  0.85 0.95]
 [1.05 1.15 1.25]]

Среднее выполнение по каждому менеджеру:
  Менеджер 1: 0.983
  Менеджер 2: 1.000
  Менеджер 3: 0.833
  Менеджер 4: 1.150

Среднее выполнение по каждому месяцу:
  Месяц 1: 0.962
  Месяц 2: 0.975
  Месяц 3: 1.038



## Задача 5. Маржа и маржинальность

```python
import numpy as np

revenue = np.array([1_200_000, 800_000, 1_500_000, 600_000, 2_000_000])
cost = np.array([900_000, 820_000, 1_100_000, 500_000, 1_850_000])
```

### Вопросы

1. Посчитай маржу по каждой сделке.
2. Посчитай маржинальность по каждой сделке.
3. Найди сделки с отрицательной маржой и сделки с маржинальностью ниже 15%.

In [38]:
import numpy as np

revenue = np.array([1_200_000, 800_000, 1_500_000, 600_000, 2_000_000])
cost = np.array([900_000, 820_000, 1_100_000, 500_000, 1_850_000])

marg = revenue - cost
print(marg)

margin = (revenue - cost) / revenue
print(margin)

bad_deal = (marg < 0) | (margin < 0.15)
bad_indices = np.where(bad_deal)[0]

for i in bad_indices:
    print(f"Сделка {i+1}: маржа={marg[i]:,.0f}₽, маржинальность={margin[i]:.1%}")

[300000 -20000 400000 100000 150000]
[ 0.25       -0.025       0.26666667  0.16666667  0.075     ]
Сделка 2: маржа=-20,000₽, маржинальность=-2.5%
Сделка 5: маржа=150,000₽, маржинальность=7.5%



## Задача 6. Булевы маски и несколько условий

```python
import numpy as np

revenue = np.array([300_000, 1_200_000, 900_000, 1_700_000, 2_500_000])
margin_rate = np.array([0.25, 0.12, 0.08, 0.18, 0.10])
days_to_ship = np.array([7, 14, 5, 20, 8])
```

### Вопросы

1. Найди сделки с выручкой выше 1 млн руб. и маржинальностью ниже 15%.
2. Найди сделки с коротким сроком отгрузки - 10 дней и меньше.
3. Проверь, какая средняя маржинальность у сделок с короткой отгрузкой.


## Задача 7. Пропуски в платежах

```python
import numpy as np

payments = np.array([150_000, 230_000, np.nan, 90_000, np.nan, 310_000, 120_000])
```

### Вопросы

1. Найди количество и долю пропущенных значений.
2. Посчитай сумму платежей без учёта пропусков.
3. Замени пропуски на медиану и посчитай новую сумму.


## Задача 8. Сортировка

```python
import numpy as np

orders = np.array([
    [5001, 1_200_000, 300_000],
    [5002, 800_000, -20_000],
    [5003, 1_500_000, 400_000],
    [5004, 600_000, 100_000],
    [5005, 2_000_000, 150_000]
])
```

Колонки:

```text
0 - order_id
1 - revenue
2 - margin
```

### Вопросы

1. Отсортируй строки по выручке по убыванию.
2. Отсортируй строки по марже по возрастанию.
3. Найди топ-3 сделки по марже.


## Задача 9. Расстояние между клиентами

```python
import numpy as np

client_1 = np.array([100_000, 12, 24])
client_2 = np.array([120_000, 10, 20])
client_3 = np.array([300_000, 2, 6])
```

Признаки:

```text
средний чек
количество заказов
срок жизни клиента в месяцах
```

### Вопросы

1. Посчитай расстояние между `client_1` и `client_2`.
2. Посчитай расстояние между `client_1` и `client_3`.
3. Определи, какой клиент ближе к `client_1`.


## Задача 10. Случайная выборка и seed

```python
import numpy as np

clients = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])
```

### Вопросы

1. Задай `seed = 2026` и выбери 3 клиентов без повторений.
2. Перемешай массив клиентов так, чтобы исходный массив не изменился.
3. Проверь, что при повторном запуске с тем же seed результат повторяется.

In [40]:
simplelist = [19, 242, 14, 152, 142, 1000]
arr = np.array(simplelist)
print(arr.mean())

261.5
