# Конспект по теории NumPy

Этот notebook предназначен для изучения NumPy в VS Code / Jupyter Notebook.

В конспекте собраны основные темы:

1. Зачем нужен NumPy  
2. Типы данных и память  
3. Массивы NumPy  
4. Свойства массивов  
5. Генерация массивов  
6. Изменение формы массивов  
7. Индексация и срезы  
8. Булевы маски  
9. Пропущенные значения  
10. Векторные операции  
11. Базовая статистика  
12. Случайные числа и выборки  

Главная идея NumPy - работать не с отдельными числами, а с массивами чисел.

In [2]:
import numpy as np

np.__version__

'2.0.2'

## 1. Зачем нужен NumPy

`NumPy` - это библиотека Python для быстрой работы с числовыми данными.

Обычный Python удобен, но при больших объёмах чисел работает медленнее, потому что каждый объект хранится довольно "тяжело": вместе со значением Python хранит дополнительную служебную информацию.

NumPy решает эту проблему за счёт массивов `ndarray`.

После импорта библиотеку обычно используют через сокращение `np`.

In [ ]:
import numpy as np

NumPy особенно полезен, когда нужно:

- хранить большие объёмы числовых данных;
- быстро выполнять расчёты по массивам;
- работать с таблицами, матрицами, векторами;
- управлять типами данных и памятью;
- генерировать случайные выборки;
- считать статистики;
- готовить данные для анализа, ML и моделирования.

## 2. Биты, байты и хранение чисел

Компьютер хранит данные в виде последовательности `0` и `1`.

Одна позиция, где может быть `0` или `1`, называется **бит**.

8 битов - это **байт**.

Количество возможных комбинаций для `n` бит:

```python
2 ** n
```

Например, в 8 битах:

```python
2 ** 8 = 256
```

То есть 1 байт может хранить 256 разных значений.

Если хранить только неотрицательные целые числа, диапазон будет:

```text
0 ... 255
```

Если хранить отрицательные и положительные числа, диапазон для 8 бит будет:

```text
-128 ... 127
```

Важно понимать: чем больше бит выделено под число, тем больший диапазон значений можно хранить, но тем больше памяти занимает каждое число.

In [ ]:
2 ** 8

## 3. Целочисленные типы данных в NumPy

В NumPy есть целочисленные типы:

```python
np.int8
np.int16
np.int32
np.int64
```

Число в названии показывает, сколько бит выделяется под одно значение.

Например, `np.int8` означает, что под число выделяется 8 бит, то есть 1 байт.

Примерные диапазоны:

```text
int8:   от -128 до 127
int16:  от -32768 до 32767
int32:  от -2147483648 до 2147483647
int64:  очень большой диапазон
```

Чтобы узнать точные границы целочисленного типа, используется функция:

```python
np.iinfo()
```

In [ ]:
np.iinfo(np.int8)

In [3]:
print(np.iinfo(np.int16))
print(np.iinfo(np.int32))
print(np.iinfo(np.int64))

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------



## 4. Беззнаковые целые типы

Беззнаковые типы хранят только неотрицательные целые числа.

Они называются:

```python
np.uint8
np.uint16
np.uint32
np.uint64
```

`u` означает `unsigned`, то есть "без знака".

Пример:

```text
uint8: от 0 до 255
```

Так как отрицательные числа не нужны, весь диапазон используется под положительные значения.

Беззнаковые типы хорошо подходят для данных вроде:

- возраст;
- количество дней;
- количество заказов;
- количество сотрудников;
- флаги и коды;
- номера категорий;
- количество товаров на складе, если оно не может быть отрицательным.

Но их нельзя бездумно использовать там, где возможны отрицательные значения: убыток, отклонение от плана, изменение баланса, дельта продаж.

In [ ]:
np.iinfo(np.uint8)

## 5. Переполнение типа

Переполнение возникает, когда число не помещается в выбранный тип данных.

Например, `int8` хранит значения только от `-128` до `127`.

Если попытаться поместить туда число больше диапазона, результат может стать неожиданным.

В старых версиях NumPy это часто приводило к "заворачиванию" значения по кругу. Например, для `uint8` значения считаются по модулю 256.

Пример логики:

```python
260 % 256 = 4
```

Поэтому число `260` при приведении к типу с диапазоном 256 значений могло превратиться в `4`.

В современных версиях NumPy часть таких операций может вызывать ошибку переполнения. Но сама идея остаётся важной: **тип данных нужно выбирать так, чтобы все реальные значения помещались в диапазон**.

In [ ]:
260 % 256

## 6. Типы с плавающей точкой

Для дробных чисел в NumPy используются:

```python
np.float16
np.float32
np.float64
np.float128
```

Чем больше число в названии, тем:

- больше памяти занимает значение;
- больше диапазон возможных чисел;
- выше точность хранения дробной части.

Чаще всего используются:

```python
np.float32
np.float64
```

`float64` обычно точнее, но занимает больше памяти.

`float32` экономнее и часто подходит для аналитики, ML и больших массивов, если не нужна высокая точность.

Информацию о float-типе можно получить через:

```python
np.finfo()
```

В результате можно увидеть:

- минимальное значение;
- максимальное значение;
- точность;
- разрешение `resolution`.

In [4]:
np.finfo(np.float32)

finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)

## 7. Почему float может быть неточным

Дробные числа в компьютере хранятся приближённо.

Поэтому не все десятичные дроби можно сохранить идеально точно.

Например, число `4.124` в `float16` может быть округлено до ближайшего доступного значения.

Это особенно важно в задачах:

- финансовых расчётов;
- расчёта комиссий;
- расчёта процентов;
- налогов;
- остатков;
- сверки платежей.

Для учебных и аналитических задач `float32` и `float64` часто подходят. Но для бухгалтерских расчётов лучше использовать специализированные подходы, например хранить деньги в копейках как целые числа или использовать decimal-логику.

In [ ]:
print(np.float16(4.12))
print(np.float16(4.13))
print(np.float16(4.123))
print(np.float16(4.124))
print(np.float16(4.125))

## 8. bool_ и str_ в NumPy

В NumPy есть свои версии булевых и строковых типов:

```python
np.bool_
np.str_
```

Они похожи на обычные Python-типы:

```python
bool
str
```

Но это не одно и то же.

На практике это важно при сравнении типов и при работе с массивами, где NumPy старается привести все элементы к единому типу.

In [5]:
print(type(True))
print(type(np.bool_(True)))

<class 'bool'>
<class 'numpy.bool'>


## 9. Что такое массив NumPy

Главная структура данных в NumPy - это массив:

```python
numpy.ndarray
```

`ndarray` означает `n-dimensional array`, то есть n-мерный массив.

Массив может быть:

- одномерным;
- двумерным;
- трёхмерным;
- многомерным.

Одномерный массив часто называют **вектором**.

Двумерный массив можно воспринимать как таблицу или матрицу.

In [6]:
arr = np.array([1, 2, 3, 4])

print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


## 10. Чем массив отличается от списка Python

Массив NumPy:

- хранит элементы одного типа;
- занимает меньше памяти;
- быстрее выполняет массовые числовые операции;
- поддерживает векторизованные вычисления;
- удобен для матриц, векторов и статистики.

Список Python:

- может хранить элементы разных типов;
- гибко меняет длину;
- удобен для общего программирования;
- менее эффективен для больших числовых расчётов.

Важная поправка к теории курса: у Python-списка доступ к элементу по индексу обычно тоже быстрый, потому что Python list реализован как динамический массив. Но NumPy всё равно выигрывает в числовых расчётах, потому что хранит данные компактнее и выполняет операции на уровне оптимизированного кода.

## 11. Создание массива

Массив создаётся с помощью:

```python
np.array()
```

Пример одномерного массива:

```python
np.array([1, 2, 3, 4])
```

Пример двумерного массива:

```python
np.array([
    [1, 2, 3],
    [4, 5, 6]
])
```

В двумерном массиве внешний список задаёт строки, внутренние списки - элементы строк.

In [ ]:
arr_1d = np.array([1, 2, 3, 4])

arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr_1d)
print(arr_2d)

## 12. Тип данных массива

У массива есть атрибут:

```python
dtype
```

Он показывает тип данных элементов массива.

При создании массива можно сразу задать тип:

```python
np.array([1, 2, 3], dtype=np.int8)
```

Это полезно, если заранее известно, какие значения будут храниться.

Например, если в массиве будут только значения от 0 до 100, можно использовать `uint8` или `int8`, а не `int64`.

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int8)

print(arr)
print(arr.dtype)

## 13. Все элементы массива имеют один тип

Это одно из главных правил NumPy.

Если в массив положить значения разных типов, NumPy попытается привести их к одному общему типу.

Например:

```python
[1, 2, 3.5]
```

скорее всего станет массивом с типом `float`.

Если в числовой массив попытаться положить строку, которую можно преобразовать в число, NumPy может её преобразовать.

Если строку нельзя преобразовать в число, возникнет ошибка.

In [7]:
arr = np.array([1, 2, 3.5])

print(arr)
print(arr.dtype)

[1.  2.  3.5]
float64


## 14. Основные свойства массива

У массива есть важные атрибуты.

### dtype

Тип данных элементов:

```python
arr.dtype
```

### ndim

Размерность массива:

```python
arr.ndim
```

Одномерный массив имеет `ndim = 1`.

Двумерный массив имеет `ndim = 2`.

### shape

Форма массива:

```python
arr.shape
```

Например, `(3, 4)` означает 3 строки и 4 столбца.

### size

Общее количество элементов:

```python
arr.size
```

Для массива формы `(3, 4)` будет 12 элементов.

### itemsize

Размер одного элемента в байтах:

```python
arr.itemsize
```

Например:

```text
int8  -> 1 байт
int16 -> 2 байта
int32 -> 4 байта
int64 -> 8 байт
```

Общий объём памяти под элементы можно посчитать так:

```python
arr.size * arr.itemsize
```

In [8]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
], dtype=np.int16)

print("dtype:", arr.dtype)
print("ndim:", arr.ndim)
print("shape:", arr.shape)
print("size:", arr.size)
print("itemsize:", arr.itemsize)
print("bytes:", arr.size * arr.itemsize)

dtype: int16
ndim: 2
shape: (2, 3)
size: 6
itemsize: 2
bytes: 12


## 15. Создание массивов из нулей

Для создания массива, заполненного нулями, используется:

```python
np.zeros()
```

Пример:

```python
np.zeros(5)
```

Создаст одномерный массив из 5 нулей.

Для двумерного массива:

```python
np.zeros((3, 4))
```

Создаст массив формы 3 на 4.

Можно указать тип:

```python
np.zeros((3, 4), dtype=np.float32)
```

Такие массивы полезны, когда нужно заранее подготовить структуру под будущие расчёты.

In [ ]:
zeros_1d = np.zeros(5)
zeros_2d = np.zeros((3, 4), dtype=np.float32)

print(zeros_1d)
print(zeros_2d)
print(zeros_2d.dtype)

## 16. np.arange

`np.arange()` создаёт массив чисел с заданным шагом.

Похож на `range`, но работает не только с целыми числами.

Правая граница не включается.

Главное отличие от `range`: `arange` может работать с дробными значениями.

Но с дробными шагами нужно быть осторожным, потому что float-арифметика может давать неточные значения.

In [9]:
print(np.arange(5))
print(np.arange(2.5, 5, 0.5))

[0 1 2 3 4]
[2.5 3.  3.5 4.  4.5]


## 17. np.linspace

`np.linspace()` создаёт заданное количество равномерно распределённых чисел между началом и концом диапазона.

Основные параметры:

```python
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
```

Где:

- `start` - начало диапазона;
- `stop` - конец диапазона;
- `num` - сколько чисел нужно создать;
- `endpoint` - включать ли правую границу;
- `retstep` - вернуть ли шаг между значениями;
- `dtype` - тип данных.

Если `endpoint=True`, правая граница включается.

Если `endpoint=False`, правая граница не включается.

`linspace` часто используется:

- для построения графиков;
- для моделирования сценариев;
- для создания равномерных шкал;
- для генерации диапазонов ставок, цен, коэффициентов.

In [ ]:
arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)

print(arr)
print("step:", step)

In [ ]:
arr, step = np.linspace(-6, 21, 60, endpoint=True, retstep=True)

print("Шаг с включённой правой границей:", round(step, 2))

arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)

print("Шаг без включения правой границы:", round(step, 2))

## 18. Изменение формы массива

Форму массива можно изменить, если общее количество элементов сохраняется.

Например, массив из 8 элементов можно превратить в форму:

```text
(2, 4)
```

или:

```text
(4, 2)
```

Но нельзя превратить в:

```text
(3, 3)
```

потому что там нужно 9 элементов.

## 19. shape и reshape

Можно изменить форму через присваивание `shape`:

```python
arr.shape = (2, 4)
```

Такой способ меняет исходный массив.

Более безопасный и частый способ - использовать:

```python
arr.reshape()
```

Например:

```python
arr.reshape((2, 4))
```

`reshape` возвращает массив новой формы.

Функция, которая позволяет получить новый массив заданной формы, - `reshape`.

In [10]:
arr = np.arange(8)

arr_new = arr.reshape((2, 4))

print("Исходный массив:")
print(arr)

print("Новая форма:")
print(arr_new)

Исходный массив:
[0 1 2 3 4 5 6 7]
Новая форма:
[[0 1 2 3]
 [4 5 6 7]]


## 20. Порядок заполнения при reshape

При изменении формы важно, в каком порядке элементы заполняют новую структуру.

По умолчанию используется порядок:

```python
order='C'
```

Это заполнение по строкам.

Есть также:

```python
order='F'
```

Это заполнение по столбцам.

В большинстве базовых задач используется стандартный порядок `C`.

In [ ]:
arr = np.arange(8)

print("order='C':")
print(arr.reshape((2, 4), order='C'))

print("order='F':")
print(arr.reshape((2, 4), order='F'))

## 21. Транспонирование

Транспонирование меняет строки и столбцы местами.

Для этого используется:

```python
arr.transpose()
```

или коротко:

```python
arr.T
```

Если была форма `(2, 4)`, после транспонирования станет `(4, 2)`.

Транспонирование часто используется при работе с матрицами, таблицами признаков, расчётами по строкам и столбцам.

In [11]:
arr = np.arange(8).reshape((2, 4))

print(arr)
print(arr.T)
print("shape before:", arr.shape)
print("shape after:", arr.T.shape)

[[0 1 2 3]
 [4 5 6 7]]
[[0 4]
 [1 5]
 [2 6]
 [3 7]]
shape before: (2, 4)
shape after: (4, 2)


## 22. Индексы и срезы

Индексация в NumPy похожа на индексацию списков Python.

Для одномерного массива:

```python
arr[0]
arr[1]
arr[-1]
```

Срезы:

```python
arr[2:5]
arr[:3]
arr[3:]
arr[::-1]
```

Для двумерного массива используется запись через запятую:

```python
matrix[row_index, column_index]
```

Например:

```python
matrix[1, 2]
```

означает элемент во второй строке и третьем столбце.

Можно брать срезы по строкам и столбцам:

```python
matrix[:, 0]      # все строки, первый столбец
matrix[0, :]      # первая строка, все столбцы
matrix[1:3, 2:4]  # строки со второй по третью и столбцы с третьего по четвёртый
```

In [12]:
matrix = np.linspace(0, 6, 12, endpoint=False).reshape(3, 4)

print(matrix)

print("Элемент [1, 2]:", matrix[1, 2])
print("Все строки, первый столбец:", matrix[:, 0])
print("Первая строка:", matrix[0, :])
print("Срез строк и столбцов:")
print(matrix[1:3, 2:4])

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
Элемент [1, 2]: 3.0
Все строки, первый столбец: [0. 2. 4.]
Первая строка: [0.  0.5 1.  1.5]
Срез строк и столбцов:
[[3.  3.5]
 [5.  5.5]]


## 23. Булевы маски

Булева маска - это массив из `True` и `False`, который показывает, какие элементы подходят под условие.

Пример:

```python
arr > 100
```

Вернёт массив:

```text
True, False, True, ...
```

Эту маску можно использовать для фильтрации:

```python
arr[arr > 100]
```

Булевы маски - один из самых важных инструментов NumPy.

Они используются для:

- отбора клиентов;
- поиска аномалий;
- фильтрации продаж;
- отбора строк с нужными условиями;
- замены значений;
- расчёта сегментов.

In [ ]:
arr = np.array([50, 120, 300, 80, 500])

mask = arr > 100

print(mask)
print(arr[mask])

## 24. Сортировка

Для сортировки есть два способа.

Первый:

```python
np.sort(arr)
```

Он возвращает новый отсортированный массив и не меняет исходный.

Второй:

```python
arr.sort()
```

Он сортирует сам исходный массив и возвращает `None`.

Это важное отличие.

Если нужно сохранить исходный порядок, лучше использовать `np.sort(arr)`.

Если исходный массив больше не нужен в прежнем виде, можно использовать `arr.sort()`.

In [13]:
arr = np.array([23, 12, 45, 12, 23, 4, 15, 3])

arr_sorted = np.sort(arr)

print("Исходный:", arr)
print("Новый отсортированный:", arr_sorted)

result = arr.sort()

print("Результат arr.sort():", result)
print("Исходный после arr.sort():", arr)

Исходный: [23 12 45 12 23  4 15  3]
Новый отсортированный: [ 3  4 12 12 15 23 23 45]
Результат arr.sort(): None
Исходный после arr.sort(): [ 3  4 12 12 15 23 23 45]


## 25. Пропущенные значения и np.nan

`np.nan` означает `Not a number`, то есть "не число".

Он появляется, когда результат числовой операции невозможен или значение отсутствует.

Например, квадратный корень из отрицательного числа в действительных числах не существует. В NumPy такая операция может дать `nan`.

Особенность `np.nan`:

```python
np.nan == np.nan
```

даёт:

```text
False
```

Поэтому `nan` нельзя нормально искать через обычное сравнение.

Для проверки используется:

```python
np.isnan()
```

Например:

```python
np.isnan(arr)
```

вернёт булеву маску, где `True` означает, что на этом месте находится `nan`.

In [ ]:
data = np.array([4, 9, -4, 3], dtype=np.float64)

roots = np.sqrt(data)

print(roots)
print(np.isnan(roots))

## 26. Почему nan опасен в расчётах

Если в массиве есть `nan`, многие итоговые расчёты тоже дадут `nan`.

Поэтому пропуски нужно обрабатывать.

Варианты обработки:

- заменить на 0;
- заменить на среднее;
- заменить на медиану;
- удалить такие значения;
- считать специальными функциями, которые игнорируют `nan`.

В NumPy есть функции:

```python
np.nanmean()
np.nanmedian()
np.nansum()
```

Они считают статистики, игнорируя `nan`.

In [14]:
arr = np.array([1, 2, np.nan, 4])

print("sum:", arr.sum())
print("nansum:", np.nansum(arr))
print("nanmean:", np.nanmean(arr))
print("nanmedian:", np.nanmedian(arr))

sum: nan
nansum: 7.0
nanmean: 2.3333333333333335
nanmedian: 2.0


## 27. Вектор в NumPy

В программировании вектор - это одномерный массив.

Например:

```python
np.array([10, 20, 30])
```

Это вектор.

Векторы используются для представления:

- продаж по месяцам;
- признаков клиента;
- весов модели;
- цен товаров;
- планов и фактов;
- рекламных расходов;
- оценок KPI.

In [ ]:
vec = np.array([10, 20, 30])

print(vec)
print(vec.ndim)

## 28. Векторные операции

Операции с NumPy-массивами обычно выполняются поэлементно.

Например:

```python
vec1 + vec2
```

означает:

```text
первый элемент + первый элемент
второй элемент + второй элемент
третий элемент + третий элемент
```

То же касается:

```python
vec1 - vec2
vec1 * vec2
vec1 / vec2
vec1 ** 2
```

Векторные операции позволяют избегать ручных циклов и считать быстрее.

In [ ]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])

print(vec1 + vec2)
print(vec1 * vec2)

## 29. Операции с массивом и числом

Если массив умножить на число, операция применится ко всем элементам.

```python
arr * 10
```

Если прибавить число:

```python
arr + 100
```

Если возвести в степень:

```python
arr ** 2
```

Это удобно для массовых пересчётов:

- увеличить цены на 5%;
- пересчитать рубли в тысячи рублей;
- применить коэффициент;
- посчитать НДС;
- рассчитать комиссию;
- нормализовать значения.

In [15]:
arr = np.array([100, 200, 300])

print(arr * 1.05)
print(arr + 100)
print(arr ** 2)

[105. 210. 315.]
[200 300 400]
[10000 40000 90000]


## 30. Сравнение массивов

Сравнение массивов тоже происходит поэлементно.

```python
arr > 100
```

вернёт массив из `True` и `False`.

Для нескольких условий используются:

```python
&   # и
|   # или
~   # не
```

Условия нужно брать в скобки:

```python
(arr > 100) & (arr < 500)
```

In [16]:
arr = np.array([50, 120, 300, 800, 40])

mask = (arr > 100) & (arr < 500)

print(mask)
print(arr[mask])

[False  True  True False False]
[120 300]


## 31. Длина вектора

Длина вектора, или норма, считается через:

```python
np.linalg.norm()
```

Например:

```python
np.linalg.norm(vec)
```

Смысл: насколько "длинный" вектор в пространстве.

В бизнес-аналитике это может использоваться не напрямую, а как часть задач похожести, расстояний и кластеризации.

In [17]:
vec = np.array([3, 4])

np.linalg.norm(vec)

np.float64(5.0)

## 32. Расстояние между векторами

Расстояние между двумя векторами можно посчитать так:

```python
np.linalg.norm(vec1 - vec2)
```

Это используется, когда нужно понять, насколько похожи два объекта.

Например:

- насколько похожи два клиента;
- насколько похожи два товара;
- насколько похожи два месяца продаж;
- насколько похожи два региона;
- насколько текущая динамика отличается от нормальной.

In [18]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])

np.linalg.norm(vec1 - vec2)

np.float64(12.206555615733702)

## 33. Скалярное произведение

Скалярное произведение считается через:

```python
np.dot(vec1, vec2)
```

Оно показывает сумму произведений соответствующих элементов.

Пример бизнес-смысла:

- количество товаров умножить на цену и получить выручку;
- веса KPI умножить на значения KPI и получить итоговую оценку;
- доли каналов умножить на доходность каналов;
- признаки клиента умножить на веса модели.

Скалярное произведение часто встречается в линейной алгебре и машинном обучении.

In [19]:
qty = np.array([10, 5, 3])
price = np.array([100, 250, 1000])

np.dot(qty, price)

np.int64(5250)

## 34. Базовая статистика

NumPy умеет быстро считать базовые статистики.

Минимум:

```python
arr.min()
```

Максимум:

```python
arr.max()
```

Среднее:

```python
arr.mean()
```

Медиана:

```python
np.median(arr)
```

Стандартное отклонение:

```python
np.std(arr)
```

Сумма:

```python
arr.sum()
```

Индекс максимума:

```python
np.argmax(arr)
```

Индекс минимума:

```python
np.argmin(arr)
```

Эти функции нужны почти в любой аналитике: продажи, клиенты, платежи, рекламные расходы, остатки, маржа, выполнение плана.

In [ ]:
arr = np.array([2, 7, 18, 28, 18, 1, 8, 4])

print("min:", arr.min())
print("max:", arr.max())
print("mean:", arr.mean())
print("median:", np.median(arr))
print("std:", np.std(arr))
print("sum:", arr.sum())
print("argmax:", np.argmax(arr))
print("argmin:", np.argmin(arr))

## 35. Случайные числа в NumPy

Случайные числа находятся в подмодуле:

```python
np.random
```

На практике компьютер генерирует не настоящие случайные числа, а псевдослучайные.

Они выглядят случайными, но создаются алгоритмом.

## 36. Генерация случайных float

Функция:

```python
np.random.rand()
```

генерирует число от 0 включительно до 1 не включительно.

Можно задать форму массива:

```python
np.random.rand(2, 3)
```

Важно: `rand` принимает форму как отдельные аргументы, а не кортеж.

In [20]:
np.random.rand(2, 3)

array([[0.98868165, 0.87903988, 0.0639583 ],
       [0.82650466, 0.53165397, 0.38089105]])

## 37. np.random.sample

`sample` тоже генерирует случайные числа от 0 до 1, но форму принимает кортежем.

```python
np.random.sample((2, 3))
```

По смыслу похожа на `rand`, но часто удобнее, если форма массива хранится в переменной.

In [21]:
shape = (2, 3)

np.random.sample(shape)

array([[0.49106298, 0.67758804, 0.70505433],
       [0.62128927, 0.48037306, 0.45617209]])

## 38. np.random.uniform

Функция:

```python
np.random.uniform(low, high, size)
```

генерирует случайные дробные числа в заданном диапазоне.

Например:

```python
np.random.uniform(1000, 5000, size=10)
```

Сгенерирует 10 случайных чисел от 1000 до 5000.

Подходит для моделирования:

- выручки;
- спроса;
- цен;
- расходов;
- сроков;
- конверсий;
- случайных колебаний.

In [ ]:
np.random.uniform(1000, 5000, size=10)

## 39. np.random.randint

Функция:

```python
np.random.randint(low, high, size)
```

генерирует случайные целые числа.

Верхняя граница не включается.

Например:

```python
np.random.randint(1, 7, size=10)
```

генерирует 10 бросков кубика со значениями от 1 до 6.

In [ ]:
np.random.randint(1, 7, size=10)

## 40. Перемешивание массивов

Для перемешивания исходного массива используется:

```python
np.random.shuffle(arr)
```

Она меняет сам массив и возвращает `None`.

Если нужно получить новый перемешанный массив, не меняя исходный, используется:

```python
np.random.permutation(arr)
```

Это важно в задачах:

- случайное распределение клиентов;
- A/B-тесты;
- перемешивание выборки;
- подготовка данных для обучения модели.

In [22]:
arr = np.arange(10)

permuted = np.random.permutation(arr)

print("Исходный:", arr)
print("Новый перемешанный:", permuted)

result = np.random.shuffle(arr)

print("Результат shuffle:", result)
print("Исходный после shuffle:", arr)

Исходный: [0 1 2 3 4 5 6 7 8 9]
Новый перемешанный: [9 2 3 1 7 8 0 5 6 4]
Результат shuffle: None
Исходный после shuffle: [4 0 8 2 3 9 5 6 1 7]


## 41. Случайная выборка

Функция:

```python
np.random.choice()
```

позволяет выбрать случайные элементы.

Основные параметры:

```python
np.random.choice(a, size=None, replace=True)
```

Где:

- `a` - массив или число;
- `size` - размер выборки;
- `replace` - можно ли выбирать с повторениями.

Если `replace=True`, один и тот же элемент может попасть в выборку несколько раз.

Если `replace=False`, выборка будет без повторений.

Без повторений обычно выбирают:

- клиентов для обзвона;
- сотрудников для проверки;
- сделки для аудита;
- товары для инвентаризации;
- участников опроса.

С повторениями моделируют процессы, где одинаковый результат может выпадать много раз:

- броски кубика;
- покупки товаров одного типа;
- случайный спрос;
- повторные обращения клиентов;
- количество заказов в день.

In [ ]:
clients = np.array([101, 102, 103, 104, 105])

print("Без повторений:", np.random.choice(clients, size=3, replace=False))
print("С повторениями:", np.random.choice(clients, size=10, replace=True))

## 42. Seed

`seed` нужен для воспроизводимости случайных чисел.

```python
np.random.seed(42)
```

После установки seed случайная последовательность будет повторяться при каждом запуске.

Это важно:

- для проверки заданий;
- для тестирования кода;
- для воспроизводимости эксперимента;
- для A/B-тестов;
- для обучения моделей;
- для сравнения разных решений на одинаковых случайных данных.

Seed должен быть целым числом в допустимом диапазоне.

In [24]:
np.random.seed(42)

np.random.randint(1, 100, size=10)

array([65, 36, 13, 99, 81, 66, 90, 24, 86, 27])

# Что важно запомнить

Главная идея NumPy - работать не с отдельными числами, а с массивами чисел.

Вместо ручного цикла:

```python
for value in values:
    ...
```

NumPy позволяет делать операции сразу:

```python
values * 1.2
```

Это называется **векторизацией**.

Для аналитика это особенно важно, потому что реальные данные почти всегда представлены наборами:

- клиенты;
- сделки;
- месяцы;
- платежи;
- товары;
- менеджеры;
- регионы;
- каналы;
- рекламные кампании;
- KPI.

NumPy даёт базу для дальнейшей работы с `pandas`, статистикой, машинным обучением и аналитическими расчётами.

In [ ]:
# Мини-пример векторизации

values = np.array([100, 200, 300, 400])

values * 1.2

# Дополнение к конспекту NumPy

Этот блок добавлен в конец конспекта отдельно. Старые разделы выше не изменялись.

Здесь собраны темы, которые понадобились при решении практических задач:

- загрузка CSV через NumPy без `pandas`;
- структурированные массивы;
- отличие обычного массива от структурированного;
- приведение типов через `.astype()`;
- проверка значений через `np.array_equal()` и `np.allclose()`;
- сбор числовой матрицы через `np.column_stack()`;
- расчёт выполнения плана;
- булевы маски и ошибка с `and` / `or`;
- маржа и маржинальность;
- добавление расчётного поля в структурированный массив;
- вывод строк как списков;
- `object`-матрицы;
- `reshape(8, 12)` для менеджеров и месяцев;
- логика `axis`;
- сортировка строк по столбцу;
- средние значения и форматированный вывод;
- простая проверка связи через группировку по маске.

## 43. Загрузка CSV в NumPy без pandas

Если работаем только через NumPy, CSV-файл можно загрузить через `np.genfromtxt()`.

```python
arr = np.genfromtxt(
    "task_02_sales_plan_fact.csv",
    delimiter=",",
    names=True,
    dtype=None,
    encoding="utf-8"
)
```

Что означают параметры:

- `delimiter=","` - разделитель колонок в CSV;
- `names=True` - первая строка файла используется как имена колонок;
- `dtype=None` - NumPy сам пытается определить типы данных;
- `encoding="utf-8"` - нужно для корректного чтения русских букв.

После загрузки можно посмотреть первые строки:

```python
print(arr[:3])
```

И структуру массива:

```python
print(arr.dtype)
```

In [ ]:
import numpy as np

arr2 = np.genfromtxt(
    "task_02_sales_plan_fact.csv",
    delimiter=",",
    names=True,
    dtype=None,
    encoding="utf-8"
)

print(arr2[:3])
print(arr2.dtype)

## 44. Структурированный массив NumPy

Когда в CSV есть разные типы данных, например строки, целые числа и дробные числа, NumPy создаёт **структурированный массив**.

Пример строки:

```python
('Иванов', '2026-01', 1453845, 949784, 4, 4, 0.855)
```

В одной строке есть разные типы:

```text
строка
строка
целое число
целое число
целое число
целое число
дробное число
```

Обычный NumPy-массив не может хранить разные типы в разных колонках как полноценную числовую матрицу.

Но структурированный массив может.

Формально у структурированного массива один общий `dtype`, но этот `dtype` составной. Внутри него у каждого поля свой тип.

## 45. Как обращаться к колонкам структурированного массива

К колонкам обращаемся по имени:

```python
manager = arr2["manager"]
month = arr2["month"]
sales_plan_rub = arr2["sales_plan_rub"]
sales_fact_rub = arr2["sales_fact_rub"]
```

Это похоже на работу с колонками таблицы.

Например, можно получить обычный числовой NumPy-массив выполнения плана:

```python
sales_completion = sales_fact_rub / sales_plan_rub
```

In [ ]:
manager = arr2["manager"]
month = arr2["month"]
sales_plan_rub = arr2["sales_plan_rub"]
sales_fact_rub = arr2["sales_fact_rub"]

sales_completion = sales_fact_rub / sales_plan_rub

print(sales_completion[:5])

## 46. Обычный массив и структурированный массив - в чём разница

Обычный NumPy-массив:

```python
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
```

У него один тип данных для всех элементов.

Структурированный массив:

```python
arr2["manager"]
arr2["sales_plan_rub"]
arr2["op_kpi"]
```

У него разные поля могут иметь разные типы.

Главное правило:

```text
Обычный массив удобен для расчётов.
Структурированный массив удобен для хранения таблицы с разными типами колонок.
```

In [ ]:
simple_arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(simple_arr.dtype)
print(arr2.dtype)

## 47. Как привести массивы к более экономным типам

Для изменения типа используется `.astype()`.

```python
new_array = old_array.astype(новый_тип)
```

Пример:

```python
age_opt = age.astype(np.uint8)
```

`.astype()` не меняет старый массив на месте. Он создаёт новый массив.

Перед приведением типа нужно проверить диапазоны:

```python
print(age.min(), age.max())
print(orders_total.min(), orders_total.max())
```

Это нужно, чтобы случайно не получить переполнение.

In [ ]:
# Пример на искусственном массиве

age = np.array([18, 25, 42, 64], dtype=np.int64)

print(age.dtype)

age_opt = age.astype(np.uint8)

print(age_opt.dtype)
print(np.array_equal(age, age_opt))

## 48. Проверка, что после смены типа значения не изменились

Для проверки одинаковости массивов используется `np.array_equal()`.

```python
np.array_equal(age, age_opt)
```

Если результат `True`, значит значения и форма массива совпадают.

Важно: `np.array_equal()` проверяет значения и форму, но не требует одинаковый `dtype`.

Для дробных чисел лучше использовать `np.allclose()`, потому что `float32` и `float64` могут немного отличаться из-за округления.

```python
np.allclose(lifetime_revenue_rub, lifetime_revenue_rub_opt)
```

In [ ]:
a = np.array([1, 2, 3], dtype=np.int64)
b = np.array([1, 2, 3], dtype=np.uint8)

print(np.array_equal(a, b))
print(a.dtype == b.dtype)

x = np.array([4.124, 10.555], dtype=np.float64)
x_opt = x.astype(np.float32)

print(np.array_equal(x, x_opt))
print(np.allclose(x, x_opt))

## 49. Как собрать числовую матрицу из нескольких колонок

Если есть структурированный массив, а нужно получить обычную числовую матрицу, можно использовать `np.column_stack()`.

```python
sales_matrix = np.column_stack([
    arr2["sales_plan_rub"],
    arr2["sales_fact_rub"],
    arr2["new_clients_plan"],
    arr2["new_clients_fact"],
    arr2["op_kpi"]
])
```

Теперь `sales_matrix` - обычный двумерный массив.

Важно: для одной колонки `column_stack()` обычно не нужен.

Лучше так:

```python
sales_plan_rub = arr2["sales_plan_rub"]
```

А не так:

```python
sales_plan_rub = np.column_stack([
    arr2["sales_plan_rub"]
])
```

In [ ]:
sales_matrix = np.column_stack([
    arr2["sales_plan_rub"],
    arr2["sales_fact_rub"],
    arr2["new_clients_plan"],
    arr2["new_clients_fact"],
    arr2["op_kpi"]
])

print(sales_matrix.shape)
print(sales_matrix.dtype)
print(sales_matrix[:3])

## 50. Расчёт выполнения плана

Выполнение плана считается так:

```text
факт / план
```

Пример:

```python
sales_completion = sales_fact_rub / sales_plan_rub
```

Если результат `1.0` - это 100%.

Если результат `1.2` - это 120%.

Если результат `0.8` - это 80%.

Вывести в процентах:

```python
print(np.round(sales_completion * 100, 2))
```

In [ ]:
sales_plan_rub = arr2["sales_plan_rub"]
sales_fact_rub = arr2["sales_fact_rub"]

sales_completion = sales_fact_rub / sales_plan_rub

print(np.round(sales_completion[:10] * 100, 2))

## 51. Ошибка с `and` и `or` в NumPy

Для NumPy-массивов нельзя использовать обычные Python-операторы:

```python
and
or
not
```

Так писать нельзя:

```python
filter_orders = (margin_rate < 0.15) and (revenue_rub > 1_000_000)
```

Потому что слева и справа не одно значение `True` / `False`, а целые массивы `True` / `False`.

Правильно использовать:

```python
&   # и
|   # или
~   # не
```

Пример:

```python
filter_orders = (margin_rate < 0.15) & (revenue_rub > 1_000_000)
```

Для нескольких условий каждое условие нужно брать в скобки.

In [ ]:
example_values = np.array([100, 500, 1_500, 2_000])

mask = (example_values > 300) & (example_values < 1_800)

print(mask)
print(example_values[mask])

## 52. Булевы маски для фильтрации строк

Булева маска - это массив из `True` и `False`.

Пример:

```python
negative_margin_mask = margin < 0
```

Чтобы отобрать строки из структурированного массива:

```python
negative_orders = arr3[negative_margin_mask]
```

Чтобы отобрать только нужные поля:

```python
negative_orders = arr3[
    ["order_id", "customer", "manager", "revenue_rub", "cost_rub", "days_to_ship"]
][negative_margin_mask]
```

Так можно получить строки в исходной структуре.

In [ ]:
arr3 = np.genfromtxt(
    "task_03_orders_margin.csv",
    delimiter=",",
    names=True,
    dtype=None,
    encoding="utf-8"
)

revenue_rub = arr3["revenue_rub"]
cost_rub = arr3["cost_rub"]

margin = revenue_rub - cost_rub

negative_margin_mask = margin < 0

negative_orders = arr3[
    ["order_id", "customer", "manager", "revenue_rub", "cost_rub", "days_to_ship"]
][negative_margin_mask]

print(negative_orders)

## 53. Маржа и маржинальность

Маржа в рублях:

```python
margin = revenue_rub - cost_rub
```

Маржинальность:

```python
margin_rate = margin / revenue_rub
```

То есть:

```text
маржинальность = маржа / выручка
```

Если маржинальность равна `0.15`, это 15%.

Если маржинальность равна `-0.03`, это -3%.

Для безопасного деления, если выручка может быть равна 0, используется `np.divide()`:

```python
margin_rate = np.divide(
    margin,
    revenue_rub,
    out=np.full(margin.shape, np.nan, dtype=np.float64),
    where=revenue_rub != 0
)
```

In [ ]:
margin_rate = np.divide(
    margin,
    revenue_rub,
    out=np.full(margin.shape, np.nan, dtype=np.float64),
    where=revenue_rub != 0
)

print(margin[:5])
print(margin_rate[:5])
print(np.round(margin_rate[:5] * 100, 2))

## 54. Как добавить расчётное поле в структурированный массив

В структурированный массив нельзя просто "добавить колонку" на месте.

Нужно создать новый структурированный массив с расширенным `dtype`.

Например, хотим добавить поле `margin_rate`:

```python
new_dtype = arr3.dtype.descr + [("margin_rate", np.float64)]
```

Затем создаём новый массив, копируем старые поля и добавляем новое поле.

In [ ]:
new_dtype = arr3.dtype.descr + [("margin_rate", np.float64)]

arr3_with_margin_rate = np.empty(
    arr3.shape,
    dtype=new_dtype
)

for field in arr3.dtype.names:
    arr3_with_margin_rate[field] = arr3[field]

arr3_with_margin_rate["margin_rate"] = margin_rate

print(arr3_with_margin_rate[:3])

Теперь можно фильтровать уже по новому полю:

```python
low_margin_orders = arr3_with_margin_rate[
    arr3_with_margin_rate["margin_rate"] < 0.15
]
```

In [ ]:
low_margin_orders = arr3_with_margin_rate[
    arr3_with_margin_rate["margin_rate"] < 0.15
]

print(low_margin_orders[:5])

## 55. Как вывести строки структурированного массива как обычные списки

Структурированный массив выводится как записи:

```python
(5001, 'Клиент_17', 'Иванов', 1365862, 954133, 5)
```

Если нужно вывести каждую строку как список:

```python
for row in order:
    print(list(row.tolist()))
```

Если нужно сохранить строки в переменную:

```python
order_rows = [list(row.tolist()) for row in order]
```

In [ ]:
order = arr3[
    ["order_id", "customer", "manager", "revenue_rub", "cost_rub", "days_to_ship"]
]

for row in order[:5]:
    print(list(row.tolist()))

## 56. Обычная матрица `object` из строк и чисел

Если нужно сделать обычную матрицу, где в одной строке есть и текст, и числа, можно использовать `dtype=object`.

```python
order_matrix = np.array(
    [list(row.tolist()) for row in order],
    dtype=object
)
```

Но важно понимать:

```text
dtype=object удобен для вывода,
но хуже подходит для быстрых числовых расчётов.
```

Для расчётов лучше использовать отдельные числовые массивы:

```python
revenue_rub = arr3["revenue_rub"]
cost_rub = arr3["cost_rub"]
margin = revenue_rub - cost_rub
```

In [ ]:
order_matrix = np.array(
    [list(row.tolist()) for row in order],
    dtype=object
)

print(order_matrix[:5])
print(order_matrix.dtype)

## 57. Как добавить маржу к `object`-матрице

Если есть матрица `order_matrix` и отдельно рассчитана маржа:

```python
margin = revenue_rub - cost_rub
```

Добавить маржу как новый столбец можно через `np.column_stack()`:

```python
order_matrix_with_margin = np.column_stack([
    order_matrix,
    margin
])
```

Теперь последняя колонка - маржа.

In [ ]:
order_matrix_with_margin = np.column_stack([
    order_matrix,
    margin
])

for row in order_matrix_with_margin[:5]:
    print(list(row))

Фильтрация по отрицательной марже:

```python
negative_margin_mask = margin < 0

negative_orders = order_matrix_with_margin[negative_margin_mask]
```

In [ ]:
negative_orders = order_matrix_with_margin[negative_margin_mask]

for row in negative_orders:
    print(list(row))

## 58. reshape и матрица менеджеры x месяцы

Если есть одномерный массив выполнения плана:

```python
sales_completion
```

и известно, что в данных 8 менеджеров и 12 месяцев, можно сделать матрицу:

```python
sales_completion_matrix = sales_completion.reshape(8, 12)
```

Форма `(8, 12)` означает:

```text
8 строк - менеджеры
12 столбцов - месяцы
```

Важно: `reshape(8, 12)` корректен только если данные заранее отсортированы так:

```text
менеджер 1 - 12 месяцев
менеджер 2 - 12 месяцев
...
менеджер 8 - 12 месяцев
```

Если порядок строк другой, сначала нужно отсортировать данные.

In [ ]:
sales_completion_matrix = sales_completion.reshape(8, 12)

print(sales_completion_matrix.shape)
print(sales_completion_matrix[:2])

## 59. Что такое axis

`axis` - это направление, вдоль которого NumPy "схлопывает" массив при расчёте.

Для матрицы формы `(8, 12)`, где:

```text
8 строк - менеджеры
12 столбцов - месяцы
```

есть две оси:

```text
axis=0 - вниз по строкам, то есть по каждому столбцу
axis=1 - вправо по столбцам, то есть по каждой строке
```

Если нужно среднее выполнение по каждому менеджеру, считаем по строкам:

```python
avg_by_manager = sales_completion_matrix.mean(axis=1)
```

Результат - 8 значений.

Если нужно среднее выполнение по каждому месяцу, считаем по столбцам:

```python
avg_by_month = sales_completion_matrix.mean(axis=0)
```

Результат - 12 значений.

Короткое правило:

```text
axis=1 - результат по строкам
axis=0 - результат по столбцам
```

In [ ]:
avg_by_manager = sales_completion_matrix.mean(axis=1)
avg_by_month = sales_completion_matrix.mean(axis=0)

print("Среднее выполнение по менеджерам:")
print(np.round(avg_by_manager * 100, 2))

print("Среднее выполнение по месяцам:")
print(np.round(avg_by_month * 100, 2))

## 60. Пример axis на маленькой матрице

```python
matrix = np.array([
    [0.8, 1.0, 1.2],
    [0.9, 1.1, 1.3]
])
```

Здесь:

```text
2 строки - менеджеры
3 столбца - месяцы
```

Среднее по каждому менеджеру:

```python
matrix.mean(axis=1)
```

Среднее по каждому месяцу:

```python
matrix.mean(axis=0)
```

In [ ]:
matrix = np.array([
    [0.8, 1.0, 1.2],
    [0.9, 1.1, 1.3]
])

print("По менеджерам:", matrix.mean(axis=1))
print("По месяцам:", matrix.mean(axis=0))

## 61. Сортировка многомерного массива

Есть два разных смысла сортировки.

### Сортировка значений внутри строк

```python
np.sort(matrix, axis=1)
```

Сортирует каждую строку отдельно.

### Сортировка значений внутри столбцов

```python
np.sort(matrix, axis=0)
```

Сортирует каждый столбец отдельно.

Но в бизнес-задачах чаще нужно не это.

Чаще нужно отсортировать **строки по выбранному столбцу**.

In [ ]:
matrix = np.array([
    [3, 1, 2],
    [9, 5, 7],
    [4, 8, 6]
])

print("Сортировка внутри строк:")
print(np.sort(matrix, axis=1))

print("Сортировка внутри столбцов:")
print(np.sort(matrix, axis=0))

## 62. Сортировка строк по конкретному столбцу

Если есть матрица `order_matrix_with_margin`, где колонки:

```text
0 - order_id
1 - customer
2 - manager
3 - revenue_rub
4 - cost_rub
5 - days_to_ship
6 - margin
```

Сортировка по выручке по возрастанию:

```python
sorted_by_revenue = order_matrix_with_margin[
    np.argsort(order_matrix_with_margin[:, 3].astype(float))
]
```

Сортировка по выручке по убыванию:

```python
sorted_by_revenue_desc = order_matrix_with_margin[
    np.argsort(order_matrix_with_margin[:, 3].astype(float))[::-1]
]
```

Сортировка по марже по убыванию:

```python
sorted_by_margin_desc = order_matrix_with_margin[
    np.argsort(order_matrix_with_margin[:, 6].astype(float))[::-1]
]
```

In [ ]:
sorted_by_margin_desc = order_matrix_with_margin[
    np.argsort(order_matrix_with_margin[:, 6].astype(float))[::-1]
]

top_5_margin_orders = sorted_by_margin_desc[:5]

for row in top_5_margin_orders:
    print(list(row))

## 63. Сортировка структурированного массива

Если работа идёт со структурированным массивом, сортировать можно по имени поля.

По выручке:

```python
sorted_arr3 = np.sort(arr3, order="revenue_rub")
```

По выручке по убыванию:

```python
sorted_arr3_desc = np.sort(arr3, order="revenue_rub")[::-1]
```

Если есть поле `margin_rate`:

```python
sorted_by_margin_rate = np.sort(
    arr3_with_margin_rate,
    order="margin_rate"
)
```

По убыванию:

```python
sorted_by_margin_rate_desc = np.sort(
    arr3_with_margin_rate,
    order="margin_rate"
)[::-1]
```

In [ ]:
sorted_arr3_desc = np.sort(arr3, order="revenue_rub")[::-1]

print(sorted_arr3_desc[:5])

## 64. Как считать среднее значение

Если есть массив маржи:

```python
margin = revenue_rub - cost_rub
```

Средняя маржа:

```python
avg_margin = margin.mean()
```

или:

```python
avg_margin = np.mean(margin)
```

Если нужна средняя маржинальность:

```python
margin_rate = margin / revenue_rub

avg_margin_rate = margin_rate.mean()
```

Нельзя писать:

```python
avg_margin = order_matrix.mean(margin)
```

Потому что `.mean()` не принимает массив как аргумент. Обычно туда передают `axis`.

In [ ]:
avg_margin = margin.mean()
avg_margin_rate = margin_rate.mean()

print(avg_margin)
print(avg_margin_rate)

## 65. Форматированный вывод через f-string

Чтобы вывести переменную внутри текста, используют `f-string`.

Неправильно:

```python
print(f"Средняя маржа: avg_margin")
```

Так выведется просто текст `avg_margin`.

Правильно:

```python
print(f"Средняя маржа: {avg_margin}")
```

Округление до двух знаков:

```python
print(f"Средняя маржа: {avg_margin:.2f}")
```

С разделением тысяч:

```python
print(f"Средняя маржа: {avg_margin:,.2f} руб.")
```

Для русского формата с пробелами вместо запятых:

```python
print(f"Средняя маржа: {avg_margin:,.2f} руб.".replace(",", " "))
```

Для процентов:

```python
print(f"Средняя маржинальность: {avg_margin_rate:.2%}")
```

In [ ]:
print(f"Средняя маржа: {avg_margin:,.2f} руб.".replace(",", " "))
print(f"Средняя маржинальность: {avg_margin_rate:.2%}")

## 66. Простая проверка связи через группировку по маске

Иногда нужно быстро проверить, есть ли связь между двумя признаками.

Например:

```text
короткий срок отгрузки
и
низкая маржинальность
```

Задаём бизнес-правила:

```python
short_ship_mask = days_to_ship <= 10
low_margin_mask = margin_rate < 0.15
```

Теперь сравним среднюю маржинальность в двух группах:

```python
avg_margin_short_ship = margin_rate[short_ship_mask].mean()
avg_margin_not_short_ship = margin_rate[~short_ship_mask].mean()
```

Знак `~` означает "не".

In [ ]:
days_to_ship = arr3["days_to_ship"]

short_ship_mask = days_to_ship <= 10
low_margin_mask = margin_rate < 0.15

avg_margin_short_ship = margin_rate[short_ship_mask].mean()
avg_margin_not_short_ship = margin_rate[~short_ship_mask].mean()

print(f"Средняя маржинальность при короткой отгрузке: {avg_margin_short_ship:.2%}")
print(f"Средняя маржинальность при обычной отгрузке: {avg_margin_not_short_ship:.2%}")

## 67. Доля низкомаржинальных сделок через `.mean()` по маске

Булев массив состоит из `True` и `False`.

В числовом смысле:

```text
True = 1
False = 0
```

Поэтому среднее по булевому массиву даёт долю `True`.

Например:

```python
low_margin_share_short_ship = low_margin_mask[short_ship_mask].mean()
low_margin_share_not_short_ship = low_margin_mask[~short_ship_mask].mean()
```

Количество сделок можно посчитать через `.sum()`:

```python
short_ship_count = short_ship_mask.sum()
not_short_ship_count = (~short_ship_mask).sum()

low_margin_short_ship_count = (short_ship_mask & low_margin_mask).sum()
low_margin_not_short_ship_count = ((~short_ship_mask) & low_margin_mask).sum()
```

In [ ]:
low_margin_share_short_ship = low_margin_mask[short_ship_mask].mean()
low_margin_share_not_short_ship = low_margin_mask[~short_ship_mask].mean()

short_ship_count = short_ship_mask.sum()
not_short_ship_count = (~short_ship_mask).sum()

low_margin_short_ship_count = (short_ship_mask & low_margin_mask).sum()
low_margin_not_short_ship_count = ((~short_ship_mask) & low_margin_mask).sum()

print("Проверка связи между короткой отгрузкой и низкой маржинальностью")
print()

print(f"Сделок с короткой отгрузкой: {short_ship_count}")
print(f"Средняя маржинальность при короткой отгрузке: {avg_margin_short_ship:.2%}")
print(f"Доля низкомаржинальных сделок при короткой отгрузке: {low_margin_share_short_ship:.2%}")
print(f"Количество низкомаржинальных сделок при короткой отгрузке: {low_margin_short_ship_count}")

print()

print(f"Сделок с обычной отгрузкой: {not_short_ship_count}")
print(f"Средняя маржинальность при обычной отгрузке: {avg_margin_not_short_ship:.2%}")
print(f"Доля низкомаржинальных сделок при обычной отгрузке: {low_margin_share_not_short_ship:.2%}")
print(f"Количество низкомаржинальных сделок при обычной отгрузке: {low_margin_not_short_ship_count}")

## 68. Как интерпретировать простую группировку по маске

Если результат такой:

```text
при короткой отгрузке средняя маржинальность ниже
и доля низкомаржинальных сделок выше
```

то можно осторожно сказать:

```text
В данных есть признак связи между коротким сроком отгрузки и низкой маржинальностью.
```

Но это не доказывает причинно-следственную связь.

Правильная формулировка:

```text
Короткие сроки отгрузки чаще встречаются вместе с низкой маржинальностью.
```

Неправильная формулировка:

```text
Короткие сроки отгрузки точно вызывают падение маржинальности.
```

Для доказательства причины нужны дополнительные проверки: больше данных, контроль других факторов, статистические тесты или модель.

## 69. Хорошая структура решения NumPy-задачи

Для практических задач удобно придерживаться одного порядка:

```python
# 1. Загрузка данных
arr = np.genfromtxt(...)

# 2. Выбор нужных колонок
revenue_rub = arr["revenue_rub"]
cost_rub = arr["cost_rub"]

# 3. Расчёт новых показателей
margin = revenue_rub - cost_rub
margin_rate = margin / revenue_rub

# 4. Создание масок
low_margin_mask = margin_rate < 0.15
high_revenue_mask = revenue_rub > 1_000_000

# 5. Фильтрация
selected_orders = arr[low_margin_mask & high_revenue_mask]

# 6. Агрегация
avg_margin_rate = margin_rate.mean()

# 7. Вывод результата
print(f"Средняя маржинальность: {avg_margin_rate:.2%}")
```

Такой порядок помогает не путаться и делает решение читаемым.